### ISSUE TITLE
Issue with LWC

### ISSUE THREAD

**Issue by mihailTr-19** [tannerrobinaugh/Salesforce-Deployment-Generator#2]
Thank you for the extention.

For me it works with Apex Classes, but doesn't work for SObject, Fields, LWC. I have an error in "Runtime Status":

"ENOENT: no such file or directory, scandir 'tmp/lwc/approvalsManagement'".

**Comment by tannerrobinaugh** [comment]
I assume this approvalsManagement folder referenced in the error message exists in your repository? Can you tell me what files exist in that folder? I'm familiar with the approvalProcesses folder but not approvalsManagement.

**Comment by tannerrobinaugh** [comment]
Would you be able to share the contents of the approvalsManagement folder please?

**Comment by tannerrobinaugh** [comment]
Actually, never mind. I think I see the problem. I will try and get an update to fix this pushed out in the next couple days. My apologies for the inconvenience.

**Comment by tannerrobinaugh** [comment]
I have fixed the issue and pushed out an update of the extension.
